apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o frappe-kube
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  ports:
  - name: "3307"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mariadb
status:
  loadBalancer: {}
