apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-socketio
  name: redis-socketio
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-socketio
    spec:
      containers:
      - args:
        - redis-server
        - /etc/conf.d/redis_cache.conf
        image: gcr.io/nana-direct-cloud/redis-socketio
        name: redis-socketio
        resources: {}
      restartPolicy: Always
status: {}
