apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rediscache
  name: rediscache
spec:
  ports:
  - name: "13000"
    port: 13000
    targetPort: 13000
  selector:
    io.kompose.service: redis-cache
status:
  loadBalancer: {}
