apiVersion: v1
kind: Service
  creationTimestamp: null
  labels:
    io.kompose.service: redissoc
  name: redissoc
spec:
  ports:
  - name: "12000"
    port: 12000
    targetPort: 12000
  selector:
    io.kompose.service: redis-socketio
status:
  loadBalancer: {}
