apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redisq
  name: redisq
spec:
  ports:
  - name: "11000"
    port: 11000
    targetPort: 11000
  selector:
    io.kompose.service: redis-queue
status:
  loadBalancer: {}
