apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o frappe-kube
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redisq
  name: redisq
spec:
  ports:
  - name: "11000"
    port: 11000
    targetPort: 11000
  selector:
    io.kompose.service: redis-queue
status:
  loadBalancer: {}
